gnome-session-inhibit: Fix redundant include of prctl.h
Including libc's prctl.h and linux's prctl.h leads to redundant
declarations of its functions. So just include libc's prctl.h since it
already includes what we need.

Otherwise the following error message can be experienced on musl libc
systems like Alpine Linux:

	In file included from ../tools/gnome-session-inhibit.c:30:
	/usr/include/sys/prctl.h:103:1: error: redefinition of struct or union 'struct prctl_mm_map'
	  103 | };
	      | ^
	In file included from ../tools/gnome-session-inhibit.c:29:
	/usr/include/linux/prctl.h:134:8: note: originally defined here
	  134 | struct prctl_mm_map {
	      |        ^~~~~~~~~~~~

Fixes: 295e8b853430 ("gnome-session-inhibit: Propagate parent death")